version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    privileged: true

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    privileged: true

  cassandra:
    image: "cassandra:3.11.9"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"

  tinyurl:
    build:
      context: .
      dockerfile: Dockerfile
    image: tinyurl:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
      - cassandra
